import Foundation
import os
#if canImport(FoundationModels)
import FoundationModels
#endif

/// A pluggable summarize/classify backend. Implementations are device-gated and selected at runtime
/// by ``TextGeneratorSelector`` — this protocol is what gets injected, never a concrete generator,
/// so the on-device and cloud paths are fully interchangeable.
///
/// Direct port of `interface TextGenerator` in `data/ai/TextGenerator.kt`. `Sendable` because it
/// crosses actor boundaries (CONVENTIONS §5).
protocol TextGenerator: Sendable {
    var name: String { get }

    /// Analyzes a bookmark. `imageUrl`, when non-nil, is a bookmark image the cloud (vision) backend
    /// can read directly; on-device/offline backends ignore it.
    ///
    /// Kotlin's `imageUrl: String? = null` default is reproduced by the protocol-extension overload
    /// below so callers may omit it.
    func analyze(text: String, ocrText: String?, sourceAbstract: String?, imageUrl: String?) async throws -> AnalysisResult
}

extension TextGenerator {
    /// Default-argument shim for the trailing `imageUrl` (Swift protocols can't carry defaults).
    func analyze(text: String, ocrText: String?, sourceAbstract: String?) async throws -> AnalysisResult {
        try await analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: nil)
    }
}

// MARK: - Cloud backend

/// Cloud backend (xAI Grok). The fallback whenever the on-device model is unavailable.
/// Port of `class CloudTextGenerator`.
final class CloudTextGenerator: TextGenerator {
    let name = "cloud-xai"
    private let xAiAnalyzer: XAiAnalyzer

    init(xAiAnalyzer: XAiAnalyzer) {
        self.xAiAnalyzer = xAiAnalyzer
    }

    func analyze(text: String, ocrText: String?, sourceAbstract: String?, imageUrl: String?) async throws -> AnalysisResult {
        if let imageUrl, !imageUrl.isBlankAI {
            return try await xAiAnalyzer.analyzeImageBookmark(
                imageUrl: imageUrl, text: text, ocrText: ocrText, sourceAbstract: sourceAbstract
            )
        } else {
            return try await xAiAnalyzer.analyzeBookmark(
                text: text, ocrText: ocrText, config: AnalysisConfig(forceLocal: false), sourceAbstract: sourceAbstract
            )
        }
    }
}

// MARK: - Local (offline keyword) backend

/// Fully-offline keyword classifier. Used when the user explicitly opts into offline mode.
/// Port of `class LocalKeywordTextGenerator`.
final class LocalKeywordTextGenerator: TextGenerator {
    let name = "local-keyword"
    private let xAiAnalyzer: XAiAnalyzer

    init(xAiAnalyzer: XAiAnalyzer) {
        self.xAiAnalyzer = xAiAnalyzer
    }

    func analyze(text: String, ocrText: String?, sourceAbstract: String?, imageUrl: String?) async throws -> AnalysisResult {
        // Kotlin ignores imageUrl here and runs the forceLocal path.
        try await xAiAnalyzer.analyzeBookmark(
            text: text, ocrText: ocrText, config: AnalysisConfig(forceLocal: true), sourceAbstract: sourceAbstract
        )
    }
}

// MARK: - On-device backend

/// Error thrown by the on-device backend when the device-gate or language/length gate rejects the
/// input. Caught inside ``TextGeneratorSelector`` and never surfaced (CONVENTIONS §3). Port of the
/// Kotlin nested `NanoTextGenerator.NanoUnavailable`.
enum NanoUnavailable: Error, LocalizedError, Equatable {
    case message(String)

    var errorDescription: String? {
        switch self {
        case let .message(message): return message
        }
    }
}

/// On-device backend (Apple Foundation Models, replacing Gemini Nano). Produces the summary
/// on-device and derives tags/category/entities with the offline keyword classifier so the whole
/// path stays network-free. Throws ``NanoUnavailable`` when the device-gate or language/length gate
/// rejects the input, so the selector can fall back to the cloud without the caller knowing.
///
/// Port of `class NanoTextGenerator`. The Android original returned `localFallback.analyze(...)`
/// wholesale with a comment that the on-device summarizer "plugs in" — here it actually plugs in:
/// the summary is generated by a `LanguageModelSession`, and tags/category/entities still come from
/// the offline classifier (network-free). If the on-device generation fails for any reason we fall
/// back to the offline summary so the contract (never throw past the gates) is preserved.
final class OnDeviceTextGenerator: TextGenerator {
    let name = "nano-on-device"

    private let availability: GenAiAvailability
    private let localFallback: LocalKeywordTextGenerator
    private static let logger = Logger(subsystem: "com.curio.app", category: "OnDeviceTextGenerator")

    init(availability: GenAiAvailability, localFallback: LocalKeywordTextGenerator) {
        self.availability = availability
        self.localFallback = localFallback
    }

    func analyze(text: String, ocrText: String?, sourceAbstract: String?, imageUrl: String?) async throws -> AnalysisResult {
        if !availability.isNanoUsable() {
            throw NanoUnavailable.message("On-device model not available on this device")
        }
        // The on-device model is text-only; an image-bearing bookmark must go to the cloud vision backend.
        if let imageUrl, !imageUrl.isBlankAI {
            throw NanoUnavailable.message("Image bookmark requires cloud vision")
        }
        // Mirrors Kotlin `listOfNotNull(sourceAbstract, text, ocrText).joinToString("\n")`.
        let combined = [sourceAbstract, text, ocrText].compactMap { $0 }.joined(separator: "\n")
        if !LanguageGate.isSupported(combined) {
            throw NanoUnavailable.message("Language not supported by on-device model (EN/JA/KO only)")
        }
        if !LanguageGate.withinCap(combined) {
            throw NanoUnavailable.message("Input exceeds on-device word cap")
        }

        Self.logger.debug("Running on-device summarization")

        // Tags/category/entities come from the offline classifier (network-free).
        let base = try await localFallback.analyze(
            text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: nil
        )

        // The summary is produced on-device by Foundation Models when available; on any failure we
        // keep the offline summary so we never break the gate-then-succeed contract.
        let summary = await summarizeOnDevice(combined) ?? base.summary

        return AnalysisResult(
            summary: summary,
            tags: base.tags,
            category: base.category,
            entities: base.entities,
            usedLocalAnalysis: base.usedLocalAnalysis
        )
    }

    /// Generates a concise TL;DR summary on-device. Returns `nil` on any unavailability/failure so
    /// the caller can fall back to the offline summary. Never throws past the gates.
    private func summarizeOnDevice(_ content: String) async -> String? {
        #if canImport(FoundationModels)
        if #available(iOS 26, *) {
            guard case .available = SystemLanguageModel.default.availability else { return nil }
            let instructions = """
            You summarize AI/ML research content into a single concise TL;DR one-liner (max 100 chars). \
            Output only the summary text. No markdown, no quotes, no preamble.
            """
            let session = LanguageModelSession(instructions: instructions)
            do {
                let response = try await session.respond(to: content)
                let trimmed = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
                return trimmed.isEmpty ? nil : trimmed
            } catch {
                Self.logger.debug("On-device summarization failed; using offline summary")
                return nil
            }
        }
        #endif
        return nil
    }
}

// MARK: - Selector

/// Routes each analysis request to the best available backend:
///  - user opted into offline mode → ``LocalKeywordTextGenerator``
///  - image-bearing bookmark → ``CloudTextGenerator`` (the on-device model can't see images)
///  - on-device available + language/length supported → ``OnDeviceTextGenerator`` (cloud on any failure)
///  - otherwise → ``CloudTextGenerator``
///
/// Port of `class TextGeneratorSelector`.
final class TextGeneratorSelector: TextGenerator {
    let name = "selector"

    private let nano: TextGenerator
    private let cloud: TextGenerator
    private let local: TextGenerator
    private let availability: GenAiAvailability
    private static let logger = Logger(subsystem: "com.curio.app", category: "TextGeneratorSelector")

    init(nano: TextGenerator, cloud: TextGenerator, local: TextGenerator, availability: GenAiAvailability) {
        self.nano = nano
        self.cloud = cloud
        self.local = local
        self.availability = availability
    }

    /// Full selector entry point with the explicit `forceLocal` flag (port of the extended Kotlin
    /// `analyze(... forceLocal: Boolean ...)`). `imageUrl` defaults to `nil`.
    func analyze(
        text: String,
        ocrText: String?,
        sourceAbstract: String?,
        forceLocal: Bool,
        imageUrl: String? = nil
    ) async throws -> AnalysisResult {
        if forceLocal {
            return try await local.analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: imageUrl)
        }

        // An image-bearing bookmark goes straight to the cloud vision backend (the on-device model can't see).
        if let imageUrl, !imageUrl.isBlankAI {
            return try await cloud.analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: imageUrl)
        }

        let combined = [sourceAbstract, text, ocrText].compactMap { $0 }.joined(separator: "\n")
        if availability.isNanoUsable() && LanguageGate.isSupported(combined) && LanguageGate.withinCap(combined) {
            do {
                return try await nano.analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: imageUrl)
            } catch let error as NanoUnavailable {
                Self.logger.debug("On-device declined (\(error.errorDescription ?? "", privacy: .public)); falling back to cloud")
                return try await cloud.analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: imageUrl)
            }
            // NOTE: a real CancellationError (or any non-NanoUnavailable error) propagates — only the
            // gate's own NanoUnavailable is swallowed into the cloud fallback, matching Kotlin's
            // `catch (e: NanoTextGenerator.NanoUnavailable)`.
        }
        return try await cloud.analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, imageUrl: imageUrl)
    }

    /// Protocol conformance: delegates with `forceLocal = false` (port of the Kotlin override).
    func analyze(text: String, ocrText: String?, sourceAbstract: String?, imageUrl: String?) async throws -> AnalysisResult {
        try await analyze(text: text, ocrText: ocrText, sourceAbstract: sourceAbstract, forceLocal: false, imageUrl: imageUrl)
    }
}

// MARK: - Blank helper

private extension String {
    /// Mirrors Kotlin `isNullOrBlank()`/`isBlank()` on a non-optional (whitespace-only ⇒ blank).
    /// Distinct name to avoid colliding with the `isBlank` extension in the Networking module.
    var isBlankAI: Bool {
        trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}
